DELETE FROM subjects;
INSERT OR IGNORE INTO subjects (id, code, name, type, credit, maxScore, semester, class_level, year) VALUES ('ท11101-ป.1', 'ท11101', 'ภาษาไทย 1', 'พื้นฐาน', 1, 100, 1, 'ป.1', NULL);
INSERT OR IGNORE INTO subjects (id, code, name, type, credit, maxScore, semester, class_level, year) VALUES ('ค11101-ป.1', 'ค11101', 'คณิตศาสตร์พื้นฐาน 1', 'พื้นฐาน', 1, 100, 1, 'ป.1', NULL);
INSERT OR IGNORE INTO subjects (id, code, name, type, credit, maxScore, semester, class_level, year) VALUES ('ว11101-ป.1', 'ว11101', 'พื้นฐานวิทยาศาสตร์ 1', 'พื้นฐาน', 1, 100, 1, 'ป.1', NULL);
INSERT OR IGNORE INTO subjects (id, code, name, type, credit, maxScore, semester, class_level, year) VALUES ('ส11101-ป.1', 'ส11101', 'สังคมศึกษา ศาสนาและวัฒนธรรม 1', 'พื้นฐาน', 1, 100, 1, 'ป.1', NULL);
INSERT OR IGNORE INTO subjects (id, code, name, type, credit, maxScore, semester, class_level, year) VALUES ('ส11102-ป.1', 'ส11102', 'ประวัติศาสตร์ 1', 'พื้นฐาน', 1, 100, 1, 'ป.1', NULL);
INSERT OR IGNORE INTO subjects (id, code, name, type, credit, maxScore, semester, class_level, year) VALUES ('พ11101-ป.1', 'พ11101', 'สุขศึกษาและพลศึกษา 1', 'พื้นฐาน', 1, 100, 1, 'ป.1', NULL);
INSERT OR IGNORE INTO subjects (id, code, name, type, credit, maxScore, semester, class_level, year) VALUES ('ศ11101-ป.1', 'ศ11101', 'ศิลปะ 1', 'พื้นฐาน', 1, 100, 1, 'ป.1', NULL);
INSERT OR IGNORE INTO subjects (id, code, name, type, credit, maxScore, semester, class_level, year) VALUES ('ง11101-ป.1', 'ง11101', 'การงานอาชีพและเทคโนโลยี 1', 'พื้นฐาน', 1, 100, 1, 'ป.1', NULL);
INSERT OR IGNORE INTO subjects (id, code, name, type, credit, maxScore, semester, class_level, year) VALUES ('อ11101-ป.1', 'อ11101', 'ภาษาอังกฤษพื้นฐาน 1', 'พื้นฐาน', 1, 100, 1, 'ป.1', NULL);
INSERT OR IGNORE INTO subjects (id, code, name, type, credit, maxScore, semester, class_level, year) VALUES ('ส11201-ป.1', 'ส11201', 'หน้าที่พลเมือง 1', 'พื้นฐาน', 1, 100, 1, 'ป.1', NULL);
INSERT OR IGNORE INTO subjects (id, code, name, type, credit, maxScore, semester, class_level, year) VALUES ('ส11202-ป.1', 'ส11202', 'การป้องกันการทุจริต 1', 'พื้นฐาน', 1, 100, 1, 'ป.1', NULL);
INSERT OR IGNORE INTO subjects (id, code, name, type, credit, maxScore, semester, class_level, year) VALUES ('ท12101-ป.2', 'ท12101', 'ภาษาไทย 2', 'พื้นฐาน', 1, 100, 1, 'ป.2', NULL);
INSERT OR IGNORE INTO subjects (id, code, name, type, credit, maxScore, semester, class_level, year) VALUES ('ค12101-ป.2', 'ค12101', 'คณิตศาสตร์พื้นฐาน 2', 'พื้นฐาน', 1, 100, 1, 'ป.2', NULL);
INSERT OR IGNORE INTO subjects (id, code, name, type, credit, maxScore, semester, class_level, year) VALUES ('ว12101-ป.2', 'ว12101', 'พื้นฐานวิทยาศาสตร์และเทคโนโลยี 2', 'พื้นฐาน', 1, 100, 1, 'ป.2', NULL);
INSERT OR IGNORE INTO subjects (id, code, name, type, credit, maxScore, semester, class_level, year) VALUES ('ส12101-ป.2', 'ส12101', 'สังคมศึกษา ศาสนาและวัฒนธรรม 2', 'พื้นฐาน', 1, 100, 1, 'ป.2', NULL);
INSERT OR IGNORE INTO subjects (id, code, name, type, credit, maxScore, semester, class_level, year) VALUES ('ส12102-ป.2', 'ส12102', 'ประวัติศาสตร์ 2', 'พื้นฐาน', 1, 100, 1, 'ป.2', NULL);
INSERT OR IGNORE INTO subjects (id, code, name, type, credit, maxScore, semester, class_level, year) VALUES ('พ12101-ป.2', 'พ12101', 'สุขศึกษาและพลศึกษา 2', 'พื้นฐาน', 1, 100, 1, 'ป.2', NULL);
INSERT OR IGNORE INTO subjects (id, code, name, type, credit, maxScore, semester, class_level, year) VALUES ('ศ12101-ป.2', 'ศ12101', 'ศิลปะ 2', 'พื้นฐาน', 1, 100, 1, 'ป.2', NULL);
INSERT OR IGNORE INTO subjects (id, code, name, type, credit, maxScore, semester, class_level, year) VALUES ('ง12101-ป.2', 'ง12101', 'การงานพื้นฐานอาชีพ 2', 'พื้นฐาน', 1, 100, 1, 'ป.2', NULL);
INSERT OR IGNORE INTO subjects (id, code, name, type, credit, maxScore, semester, class_level, year) VALUES ('อ12101-ป.2', 'อ12101', 'ภาษาอังกฤษพื้นฐาน 2', 'พื้นฐาน', 1, 100, 1, 'ป.2', NULL);
INSERT OR IGNORE INTO subjects (id, code, name, type, credit, maxScore, semester, class_level, year) VALUES ('ส12201-ป.2', 'ส12201', 'หน้าที่พลเมือง 2', 'พื้นฐาน', 1, 100, 1, 'ป.2', NULL);
INSERT OR IGNORE INTO subjects (id, code, name, type, credit, maxScore, semester, class_level, year) VALUES ('ส12202-ป.2', 'ส12202', 'การป้องกันการทุจริต 2', 'พื้นฐาน', 1, 100, 1, 'ป.2', NULL);
INSERT OR IGNORE INTO subjects (id, code, name, type, credit, maxScore, semester, class_level, year) VALUES ('ท13101-ป.3', 'ท13101', 'ภาษาไทย 3', 'พื้นฐาน', 1, 100, 1, 'ป.3', NULL);
INSERT OR IGNORE INTO subjects (id, code, name, type, credit, maxScore, semester, class_level, year) VALUES ('ค13101-ป.3', 'ค13101', 'คณิตศาสตร์พื้นฐาน 3', 'พื้นฐาน', 1, 100, 1, 'ป.3', NULL);
INSERT OR IGNORE INTO subjects (id, code, name, type, credit, maxScore, semester, class_level, year) VALUES ('ว13101-ป.3', 'ว13101', 'พื้นฐานวิทยาศาสตร์และเทคโนโลยี 3', 'พื้นฐาน', 1, 100, 1, 'ป.3', NULL);
INSERT OR IGNORE INTO subjects (id, code, name, type, credit, maxScore, semester, class_level, year) VALUES ('ส13101-ป.3', 'ส13101', 'สังคมศึกษา ศาสนาและวัฒนธรรม  3', 'พื้นฐาน', 1, 100, 1, 'ป.3', NULL);
INSERT OR IGNORE INTO subjects (id, code, name, type, credit, maxScore, semester, class_level, year) VALUES ('ส13102-ป.3', 'ส13102', 'ประวัติศาสตร์ 3', 'พื้นฐาน', 1, 100, 1, 'ป.3', NULL);
INSERT OR IGNORE INTO subjects (id, code, name, type, credit, maxScore, semester, class_level, year) VALUES ('พ13101-ป.3', 'พ13101', 'สุขศึกษาและพลศึกษา 3', 'พื้นฐาน', 1, 100, 1, 'ป.3', NULL);
INSERT OR IGNORE INTO subjects (id, code, name, type, credit, maxScore, semester, class_level, year) VALUES ('ศ13101-ป.3', 'ศ13101', 'ศิลปะ 3', 'พื้นฐาน', 1, 100, 1, 'ป.3', NULL);
INSERT OR IGNORE INTO subjects (id, code, name, type, credit, maxScore, semester, class_level, year) VALUES ('ง13101-ป.3', 'ง13101', 'การงานพื้นฐานอาชีพ 3', 'พื้นฐาน', 1, 100, 1, 'ป.3', NULL);
INSERT OR IGNORE INTO subjects (id, code, name, type, credit, maxScore, semester, class_level, year) VALUES ('อ13101-ป.3', 'อ13101', 'ภาษาอังกฤษพื้นฐาน 3', 'พื้นฐาน', 1, 100, 1, 'ป.3', NULL);
INSERT OR IGNORE INTO subjects (id, code, name, type, credit, maxScore, semester, class_level, year) VALUES ('ส13201-ป.3', 'ส13201', 'หน้าที่พลเมือง 3', 'พื้นฐาน', 1, 100, 1, 'ป.3', NULL);
INSERT OR IGNORE INTO subjects (id, code, name, type, credit, maxScore, semester, class_level, year) VALUES ('ส13202-ป.3', 'ส13202', 'การป้องกันการทุจริต 3', 'พื้นฐาน', 1, 100, 1, 'ป.3', NULL);
INSERT OR IGNORE INTO subjects (id, code, name, type, credit, maxScore, semester, class_level, year) VALUES ('ท14101-ป.4', 'ท14101', 'ภาษาไทย 4', 'พื้นฐาน', 1, 100, 1, 'ป.4', NULL);
INSERT OR IGNORE INTO subjects (id, code, name, type, credit, maxScore, semester, class_level, year) VALUES ('ค14101-ป.4', 'ค14101', 'คณิตศาสตร์พื้นฐาน 4', 'พื้นฐาน', 1, 100, 1, 'ป.4', NULL);
INSERT OR IGNORE INTO subjects (id, code, name, type, credit, maxScore, semester, class_level, year) VALUES ('ว14101-ป.4', 'ว14101', 'พื้นฐานวิทยาศาสตร์และเทคโนโลยี 4', 'พื้นฐาน', 1, 100, 1, 'ป.4', NULL);
INSERT OR IGNORE INTO subjects (id, code, name, type, credit, maxScore, semester, class_level, year) VALUES ('ส14101-ป.4', 'ส14101', 'สังคมศึกษา ศาสนาและวัฒนธรรม 4', 'พื้นฐาน', 1, 100, 1, 'ป.4', NULL);
INSERT OR IGNORE INTO subjects (id, code, name, type, credit, maxScore, semester, class_level, year) VALUES ('ส14102-ป.4', 'ส14102', 'ประวัติศาสตร์ 4', 'พื้นฐาน', 1, 100, 1, 'ป.4', NULL);
INSERT OR IGNORE INTO subjects (id, code, name, type, credit, maxScore, semester, class_level, year) VALUES ('พ14101-ป.4', 'พ14101', 'สุขศึกษาและพลศึกษา 4', 'พื้นฐาน', 1, 100, 1, 'ป.4', NULL);
INSERT OR IGNORE INTO subjects (id, code, name, type, credit, maxScore, semester, class_level, year) VALUES ('ศ14101-ป.4', 'ศ14101', 'ศิลปะ 4', 'พื้นฐาน', 1, 100, 1, 'ป.4', NULL);
INSERT OR IGNORE INTO subjects (id, code, name, type, credit, maxScore, semester, class_level, year) VALUES ('ง14101-ป.4', 'ง14101', 'การงานพื้นฐานอาชีพ 4', 'พื้นฐาน', 1, 100, 1, 'ป.4', NULL);
INSERT OR IGNORE INTO subjects (id, code, name, type, credit, maxScore, semester, class_level, year) VALUES ('อ14101-ป.4', 'อ14101', 'ภาษาอังกฤษพื้นฐาน 4', 'พื้นฐาน', 1, 100, 1, 'ป.4', NULL);
INSERT OR IGNORE INTO subjects (id, code, name, type, credit, maxScore, semester, class_level, year) VALUES ('ส14201-ป.4', 'ส14201', 'หน้าที่พลเมือง 4', 'พื้นฐาน', 1, 100, 1, 'ป.4', NULL);
INSERT OR IGNORE INTO subjects (id, code, name, type, credit, maxScore, semester, class_level, year) VALUES ('ส14202-ป.4', 'ส14202', 'การป้องกันการทุจริต 4', 'พื้นฐาน', 1, 100, 1, 'ป.4', NULL);
INSERT OR IGNORE INTO subjects (id, code, name, type, credit, maxScore, semester, class_level, year) VALUES ('ท15101-ป.5', 'ท15101', 'ภาษาไทย 5', 'พื้นฐาน', 1, 100, 1, 'ป.5', NULL);
INSERT OR IGNORE INTO subjects (id, code, name, type, credit, maxScore, semester, class_level, year) VALUES ('ค15101-ป.5', 'ค15101', 'คณิตศาสตร์พื้นฐาน 5', 'พื้นฐาน', 1, 100, 1, 'ป.5', NULL);
INSERT OR IGNORE INTO subjects (id, code, name, type, credit, maxScore, semester, class_level, year) VALUES ('ว15101-ป.5', 'ว15101', 'พื้นฐานวิทยาศาสตร์และเทคโนโลยี 5', 'พื้นฐาน', 1, 100, 1, 'ป.5', NULL);
INSERT OR IGNORE INTO subjects (id, code, name, type, credit, maxScore, semester, class_level, year) VALUES ('ส15101-ป.5', 'ส15101', 'สังคมศึกษา ศาสนาและวัฒนธรรม 5', 'พื้นฐาน', 1, 100, 1, 'ป.5', NULL);
INSERT OR IGNORE INTO subjects (id, code, name, type, credit, maxScore, semester, class_level, year) VALUES ('ส15102-ป.5', 'ส15102', 'ประวัติศาสตร์ 5', 'พื้นฐาน', 1, 100, 1, 'ป.5', NULL);
INSERT OR IGNORE INTO subjects (id, code, name, type, credit, maxScore, semester, class_level, year) VALUES ('พ15101-ป.5', 'พ15101', 'สุขศึกษาและพลศึกษา 5', 'พื้นฐาน', 1, 100, 1, 'ป.5', NULL);
INSERT OR IGNORE INTO subjects (id, code, name, type, credit, maxScore, semester, class_level, year) VALUES ('ศ15101-ป.5', 'ศ15101', 'ศิลปะ 5', 'พื้นฐาน', 1, 100, 1, 'ป.5', NULL);
INSERT OR IGNORE INTO subjects (id, code, name, type, credit, maxScore, semester, class_level, year) VALUES ('ง15101-ป.5', 'ง15101', 'การงานพื้นฐานอาชีพ 5', 'พื้นฐาน', 1, 100, 1, 'ป.5', NULL);
INSERT OR IGNORE INTO subjects (id, code, name, type, credit, maxScore, semester, class_level, year) VALUES ('อ15101-ป.5', 'อ15101', 'ภาษาอังกฤษพื้นฐาน 5', 'พื้นฐาน', 1, 100, 1, 'ป.5', NULL);
INSERT OR IGNORE INTO subjects (id, code, name, type, credit, maxScore, semester, class_level, year) VALUES ('ส15201-ป.5', 'ส15201', 'หน้าที่พลเมือง 5', 'พื้นฐาน', 1, 100, 1, 'ป.5', NULL);
INSERT OR IGNORE INTO subjects (id, code, name, type, credit, maxScore, semester, class_level, year) VALUES ('ส15202-ป.5', 'ส15202', 'การป้องกันการทุจริต 5', 'พื้นฐาน', 1, 100, 1, 'ป.5', NULL);
INSERT OR IGNORE INTO subjects (id, code, name, type, credit, maxScore, semester, class_level, year) VALUES ('ท16101-ป.6', 'ท16101', 'ภาษาไทย 6', 'พื้นฐาน', 1, 100, 1, 'ป.6', NULL);
INSERT OR IGNORE INTO subjects (id, code, name, type, credit, maxScore, semester, class_level, year) VALUES ('ค16101-ป.6', 'ค16101', 'คณิตศาสตร์พื้นฐาน 6', 'พื้นฐาน', 1, 100, 1, 'ป.6', NULL);
INSERT OR IGNORE INTO subjects (id, code, name, type, credit, maxScore, semester, class_level, year) VALUES ('ว16101-ป.6', 'ว16101', 'พื้นฐานวิทยาศาสตร์และเทคโนโลยี 6', 'พื้นฐาน', 1, 100, 1, 'ป.6', NULL);
INSERT OR IGNORE INTO subjects (id, code, name, type, credit, maxScore, semester, class_level, year) VALUES ('ส16101-ป.6', 'ส16101', 'สังคมศึกษา ศาสนาและวัฒนธรรม 6', 'พื้นฐาน', 1, 100, 1, 'ป.6', NULL);
INSERT OR IGNORE INTO subjects (id, code, name, type, credit, maxScore, semester, class_level, year) VALUES ('ส16102-ป.6', 'ส16102', 'ประวัติศาสตร์ 6', 'พื้นฐาน', 1, 100, 1, 'ป.6', NULL);
INSERT OR IGNORE INTO subjects (id, code, name, type, credit, maxScore, semester, class_level, year) VALUES ('พ16101-ป.6', 'พ16101', 'สุขศึกษาและพลศึกษา 6', 'พื้นฐาน', 1, 100, 1, 'ป.6', NULL);
INSERT OR IGNORE INTO subjects (id, code, name, type, credit, maxScore, semester, class_level, year) VALUES ('ศ16101-ป.6', 'ศ16101', 'ศิลปะ 6', 'พื้นฐาน', 1, 100, 1, 'ป.6', NULL);
INSERT OR IGNORE INTO subjects (id, code, name, type, credit, maxScore, semester, class_level, year) VALUES ('ง16101-ป.6', 'ง16101', 'การงานพื้นฐานอาชีพ 6', 'พื้นฐาน', 1, 100, 1, 'ป.6', NULL);
INSERT OR IGNORE INTO subjects (id, code, name, type, credit, maxScore, semester, class_level, year) VALUES ('อ16101-ป.6', 'อ16101', 'ภาษาอังกฤษพื้นฐาน 6', 'พื้นฐาน', 1, 100, 1, 'ป.6', NULL);
INSERT OR IGNORE INTO subjects (id, code, name, type, credit, maxScore, semester, class_level, year) VALUES ('ส16201-ป.6', 'ส16201', 'หน้าที่พลเมือง 6', 'พื้นฐาน', 1, 100, 1, 'ป.6', NULL);
INSERT OR IGNORE INTO subjects (id, code, name, type, credit, maxScore, semester, class_level, year) VALUES ('ส16202-ป.6', 'ส16202', 'การป้องกันการทุจริต 6', 'พื้นฐาน', 1, 100, 1, 'ป.6', NULL);
INSERT OR IGNORE INTO subjects (id, code, name, type, credit, maxScore, semester, class_level, year) VALUES ('ก11901-ป.1', 'ก11901', 'แนะแนว 1', 'พื้นฐาน', 1, 100, 1, 'ป.1', NULL);
INSERT OR IGNORE INTO subjects (id, code, name, type, credit, maxScore, semester, class_level, year) VALUES ('ก11902-ป.1', 'ก11902', 'ลูกเสือ-เนตรนารี 1', 'พื้นฐาน', 1, 100, 1, 'ป.1', NULL);
INSERT OR IGNORE INTO subjects (id, code, name, type, credit, maxScore, semester, class_level, year) VALUES ('ก11903-ป.1', 'ก11903', 'สนุกกับศิลปะ', 'พื้นฐาน', 1, 100, 1, 'ป.1', NULL);
INSERT OR IGNORE INTO subjects (id, code, name, type, credit, maxScore, semester, class_level, year) VALUES ('ก11904-ป.1', 'ก11904', 'กิจกรรมเพื่อสังคมและสาธารณประโยชน์', 'พื้นฐาน', 1, 100, 1, 'ป.1', NULL);
INSERT OR IGNORE INTO subjects (id, code, name, type, credit, maxScore, semester, class_level, year) VALUES ('ก12901-ป.2', 'ก12901', 'แนะแนว 2', 'พื้นฐาน', 1, 100, 1, 'ป.2', NULL);
INSERT OR IGNORE INTO subjects (id, code, name, type, credit, maxScore, semester, class_level, year) VALUES ('ก12902-ป.2', 'ก12902', 'ลูกเสือ-เนตรนารี 2', 'พื้นฐาน', 1, 100, 1, 'ป.2', NULL);
INSERT OR IGNORE INTO subjects (id, code, name, type, credit, maxScore, semester, class_level, year) VALUES ('ก12903-ป.2', 'ก12903', 'การละเล่นพื้นบ้าน', 'พื้นฐาน', 1, 100, 1, 'ป.2', NULL);
INSERT OR IGNORE INTO subjects (id, code, name, type, credit, maxScore, semester, class_level, year) VALUES ('ก12904-ป.2', 'ก12904', 'กิจกรรมเพื่อสังคมและสาธารณประโยชน์', 'พื้นฐาน', 1, 100, 1, 'ป.2', NULL);
INSERT OR IGNORE INTO subjects (id, code, name, type, credit, maxScore, semester, class_level, year) VALUES ('ก13901-ป.3', 'ก13901', 'แนะแนว 3', 'พื้นฐาน', 1, 100, 1, 'ป.3', NULL);
INSERT OR IGNORE INTO subjects (id, code, name, type, credit, maxScore, semester, class_level, year) VALUES ('ก13902-ป.3', 'ก13902', 'ลูกเสือ-เนตรนารี 3', 'พื้นฐาน', 1, 100, 1, 'ป.3', NULL);
INSERT OR IGNORE INTO subjects (id, code, name, type, credit, maxScore, semester, class_level, year) VALUES ('ก13903-ป.3', 'ก13903', 'ชุมนุมศิลปะการพับกระดาษ', 'พื้นฐาน', 1, 100, 1, 'ป.3', NULL);
INSERT OR IGNORE INTO subjects (id, code, name, type, credit, maxScore, semester, class_level, year) VALUES ('ก13904-ป.3', 'ก13904', 'กิจกรรมเพื่อสังคมและสาธารณประโยชน์', 'พื้นฐาน', 1, 100, 1, 'ป.3', NULL);
INSERT OR IGNORE INTO subjects (id, code, name, type, credit, maxScore, semester, class_level, year) VALUES ('ก14901-ป.4', 'ก14901', 'แนะแนว 4', 'พื้นฐาน', 1, 100, 1, 'ป.4', NULL);
INSERT OR IGNORE INTO subjects (id, code, name, type, credit, maxScore, semester, class_level, year) VALUES ('ก14902-ป.4', 'ก14902', 'ลูกเสือ-เนตรนารี 4', 'พื้นฐาน', 1, 100, 1, 'ป.4', NULL);
INSERT OR IGNORE INTO subjects (id, code, name, type, credit, maxScore, semester, class_level, year) VALUES ('ก14903-ป.4', 'ก14903', 'ชุมนุมกีฬา1', 'พื้นฐาน', 1, 100, 1, 'ป.4', NULL);
INSERT OR IGNORE INTO subjects (id, code, name, type, credit, maxScore, semester, class_level, year) VALUES ('ก14904-ป.4', 'ก14904', 'กิจกรรมเพื่อสังคมและสาธารณประโยชน์', 'พื้นฐาน', 1, 100, 1, 'ป.4', NULL);
INSERT OR IGNORE INTO subjects (id, code, name, type, credit, maxScore, semester, class_level, year) VALUES ('ก15901-ป.5', 'ก15901', 'แนะแนว 5', 'พื้นฐาน', 1, 100, 1, 'ป.5', NULL);
INSERT OR IGNORE INTO subjects (id, code, name, type, credit, maxScore, semester, class_level, year) VALUES ('ก15902-ป.5', 'ก15902', 'ลูกเสือ-เนตรนารี 5', 'พื้นฐาน', 1, 100, 1, 'ป.5', NULL);
INSERT OR IGNORE INTO subjects (id, code, name, type, credit, maxScore, semester, class_level, year) VALUES ('ก15903-ป.5', 'ก15903', 'ชุมนุมกีฬา2', 'พื้นฐาน', 1, 100, 1, 'ป.5', NULL);
INSERT OR IGNORE INTO subjects (id, code, name, type, credit, maxScore, semester, class_level, year) VALUES ('ก15904-ป.5', 'ก15904', 'กิจกรรมเพื่อสังคมและสาธารณประโยชน์', 'พื้นฐาน', 1, 100, 1, 'ป.5', NULL);
INSERT OR IGNORE INTO subjects (id, code, name, type, credit, maxScore, semester, class_level, year) VALUES ('ก16901-ป.6', 'ก16901', 'แนะแนว 6', 'พื้นฐาน', 1, 100, 1, 'ป.6', NULL);
INSERT OR IGNORE INTO subjects (id, code, name, type, credit, maxScore, semester, class_level, year) VALUES ('ก16902-ป.6', 'ก16902', 'ลูกเสือ-เนตรนารี 6', 'พื้นฐาน', 1, 100, 1, 'ป.6', NULL);
INSERT OR IGNORE INTO subjects (id, code, name, type, credit, maxScore, semester, class_level, year) VALUES ('ก16903-ป.6', 'ก16903', 'ชุมนุมกีฬา3', 'พื้นฐาน', 1, 100, 1, 'ป.6', NULL);
INSERT OR IGNORE INTO subjects (id, code, name, type, credit, maxScore, semester, class_level, year) VALUES ('ก16904-ป.6', 'ก16904', 'กิจกรรมเพื่อสังคมและสาธารณประโยชน์', 'พื้นฐาน', 1, 100, 1, 'ป.6', NULL);
